### ISSUE TITLE
Assets handling to integration with sdk api

### ISSUE THREAD

**Issue by azopat** [k8-proxy/go-k8s-srv#17]
Please increase the exxpiration time for presigned urls from 2min to maybe 5min in order to allow mohit to get it on his integration.
Also do not delete anymore the assets right away, but maybe schedule deletion in the next 5min

**Comment by mahnouman** [comment]
@haitham911 please change this from 24 hours to 10 minutes:
	presignedUrlExpireIn = time.Hour * 24

Which is: cmd/main.go

**Comment by haitham911** [comment]
it's done https://github.com/k8-proxy/go-k8s-srv/pull/45
