### ISSUE TITLE
Testing of srv

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-srv#3]
Please do a functional testing of this repo, srv develop branch, (this repo) should provide both the functionality of srv1 and srv2. Mention where you are stuck if you got stuck.

**Comment by mohammedbakr** [comment]
I had problem when following with the readme file with minio
the log of it was:
```
2021/04/26 09:46:00 Get "http://localhost:9000/test/?location=": dial tcp 127.0.0.1:9000: connect: connection refused
```
But I solved with the same instruction for RabbitMQ
I got the minio IPAddress by running:
```
docker inspect <minio_container_name>

```
then in the docker build I replaced `<minio-endpoint>` with the output of the command and it worked

**Comment by mahnouman** [comment]
Hi @himanshu2464 appreciate doing a test drive of this code, which is srv ,,,, srv should be replacing both srv1 and srv2 , so the idea is that if you terminate both srv1 and srv2 pods and instead fired up srv, the solution should still be functioning delivering rebuilt files along with their reports

**Comment by mahnouman** [comment]
Hi @azopat please do the same, thank you.

**Comment by himanshu2464** [comment]
root@ip-172-31-4-220:/home/ubuntu# kubectl logs -f srv-776699d877-lvvfv -n icap-adaptation
2021/05/11 12:46:46 Waiting for messages
{"level":"info","time":"2021-05-11T15:13:54Z","message":"adaptation request consumer  received message from queue "}
{"level":"info","fileID":"160dabb1-54e3-498f-9e52-1aae21c47c11","rebuilt-file-location":"/var/source/160dabb1-54e3-498f-9e52-1aae21c47c11","source-file-location":"/var/target/160dabb1-54e3-498f-9e52-1aae21c47c11","time":"2021-05-11T15:13:54Z"}
{"level":"info","time":"2021-05-11T15:13:54Z","message":"file uploaded to minio successfully"}
{"level":"info","Exchange":"processing-request-exchange","RoutingKey":"processing-request","time":"2021-05-11T15:13:54Z","message":"message published to queue "}
{"level":"info","time":"2021-05-11T15:13:54Z","message":" processingOutcome consumer received message from queue "}
{"level":"error","error":"error downloading file from minio : open /var/target/160dabb1-54e3-498f-9e52-1aae21c47c11: no such file or directory","time":"2021-05-11T15:13:54Z","message":"error processingOutcome consumer Failed to process message"}

i tried with the deployment of this service on Kubernetes and i am getting the above error it is not able to find the in minio.

**Comment by himanshu2464** [comment]
the SRV is not able to send files back to icap-server.

**Comment by azopat** [comment]
@mahnouman  
I did the test, it works well now. we just had to add the target volume to the deployment.
Should i update the helm charts and switch to this configuration ?

**Comment by mahnouman** [comment]
Hi @azopat yes please

**Comment by himanshu2464** [comment]
this is a working file by updating the config.

![image](https://user-images.githubusercontent.com/45463238/118321613-749b2080-b51b-11eb-9b85-ef46e8d576e7.png)

![image](https://user-images.githubusercontent.com/45463238/118321691-94cadf80-b51b-11eb-8403-b44737402ccd.png)

should I update helm charts with the updated config?

**Comment by azopat** [comment]
all done here and helm chart of infra updated and testing. everything is well. we have now switched to SRV and removed srv1 and srv2
thanks

**Comment by mahnouman** [comment]
Thanks @azopat we will proceed closing this.
