### ISSUE TITLE
Disable deletion for minio files by env parameter

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-srv#38]
Just for troubleshooting purposes, the developers might require disabling deletion of files as a method to troubleshoot, we need to do this by env variable and incase the env variable is not provided with the expected value, or not provided at all the default will be to keep deleting files.

**Comment by GINAGC** [comment]
@Lestat06 please review this one.

**Comment by Lestat06** [comment]
@mahnouman i need more info on where to find that env variable

**Comment by GINAGC** [comment]
@mahnouman can you explain what was the change here?

**Comment by Lestat06** [comment]
@GINAGC this is available now in minutes. locally and from helm command

**Comment by GINAGC** [comment]
@Lestat06 should we move this one to release?

**Comment by Lestat06** [comment]
@GINAGC  yes this is ready thank you
