### ISSUE TITLE
Verify maintaining rabbitmq headers all the time

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-srv#39]
Rabbitmq headers are used to relate events in Jaeger, we need to keep it intact even in the case of a file failed to process or similar, please verify that this is the behavior either in this repo or process.

**Comment by GINAGC** [comment]
@ibrahimk9000 please take a look to this one.

**Comment by GINAGC** [comment]
@ibrahimk9000 any update here?

**Comment by GINAGC** [comment]
From Ibrahim: it is just monitoring if the header file is returned correctly , and till the day there is  no problem detected related to  the rabbitmq header ,

We are closing for now.
